# server配置
server:
  port: 8080
  servlet:
    context-path: /
#连接池配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql:///sm_db
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
# mybatis-plus的配置
mybatis-plus:
  type-aliases-package: com.horo.pojo
  global-config:
    db-config:
      logic-delete-field: isDeleted #全局逻辑删除
      id-type: auto #主键策略自增长
      table-prefix: news_  #设置表的前置

#配置jwt
jwt:
  token:
    tokenExpiration: 120 #有效时间，单位秒
    tokenSignKey: headLine123456 #自定义的签名秘钥

